SELECT * FROM IncomeExpenses
SELECT * FROM [NEPALSEVA].DBO.IncomeExp
GO
SELECT * FROM [NEPALSEVA].DBO.IncomeExp
WHERE IE_ParentID NOT IN (SELECT IE_ID FROM [NEPALSEVA].DBO.IncomeExp
)
GO
SET IDENTITY_INSERT IncomeExpenses ON
INSERT INTO IncomeExpenses(ID, CODE,	IE,	PARENTID,	ISENABLE,	PREVSYSID,	CREATEDON)
SELECT IE_ID, IE_CODE, IE,IIF(IE_PARENTID=0, NULL, IE_PARENTID ), ISNEEDED, IE_ID, GETDATE() FROM [NEPALSEVA].DBO.IncomeExp
SET IDENTITY_INSERT IncomeExpenses OFF
GO
UPDATE A
SET A.PARENTID = IIF(B.LA_PARENTID=0, NULL, B.LA_PARENTID )
FROM IncomeExpenses A 
JOIN [NEPALSEVA].DBO.IncomeExp B WITH(NOLOCK) ON A.ID = B.IE_ID

