SELECT * FROM LIABILITYASSETS
SELECT * FROM [NEPALSEVA].DBO.LA
GO
SELECT * FROM [NEPALSEVA].DBO.LA
WHERE LA_ParentID NOT IN (SELECT LA_ID FROM [NEPALSEVA].DBO.LA
)
GO
SET IDENTITY_INSERT LIABILITYASSETS ON
INSERT INTO LIABILITYASSETS(ID, CODE,	LA,	PARENTID,	ISENABLE,	PREVSYSID,	CREATEDON)
SELECT LA_ID, LA_CODE, LA,NULL, ISNEEDED, LA_ID, GETDATE() FROM [NEPALSEVA].DBO.LA
SET IDENTITY_INSERT LIABILITYASSETS OFF
GO
UPDATE A
SET A.PARENTID = IIF(B.LA_PARENTID=0, NULL, B.LA_PARENTID )
FROM LIABILITYASSETS A 
JOIN [NEPALSEVA].DBO.LA B WITH(NOLOCK) ON A.ID = B.LA_ID

