--select * from [identity].MenuList
--IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Home')
--BEGIN
--	INSERT INTO [IDENTITY].MENULIST (MENUNAME,MENUNAMENEPALI,ICON,PATH)
--	SELECT'Home',N'होम','fas fa-Home','/'
--END

IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Hangfire')
BEGIN
	INSERT INTO [IDENTITY].MENULIST (MENUNAME,MENUNAMENEPALI,ICON,PATH)
	SELECT'Hangfire','Hangfire','fas fa-briefcase','/jobs'
END

IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Quick Start Guide')
BEGIN
	INSERT INTO [IDENTITY].MENULIST (MENUNAME,MENUNAMENEPALI,ICON,PATH)
	SELECT'Quick Start Guide',N'कुइक स्टार्ट गाईड ','fad fa-arrow-from-left','https://codewithmukesh.com/blog/blazor-hero-quick-start-guide/'
END

IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Swagger')
BEGIN
	INSERT INTO [IDENTITY].MENULIST (MENUNAME,MENUNAMENEPALI,ICON,PATH)
	SELECT 'Swagger',N'स्वाग्गर','','/swagger/index.html'
END

IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Dashboard')
BEGIN
	INSERT INTO [IDENTITY].MENULIST (MENUNAME,MENUNAMENEPALI,ICON,PATH)
	SELECT 'Dashboard',N'ड्यास्बोर्ड','fas fa-th-list','/dashboard'
END

IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Account')
BEGIN
	INSERT INTO [IDENTITY].MENULIST (MENUNAME,MENUNAMENEPALI,ICON,PATH)
	SELECT 'Account',N'खाता','fas fa-user-friends','/account'
END

IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Audit Trails')
BEGIN
		INSERT INTO [IDENTITY].MENULIST (MENUNAME,MENUNAMENEPALI,ICON,PATH)
		SELECT 'Audit Trails',N'अडिट ट्रायल','fab fa-delicious','/audit-trails'
END

IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Document Management')
BEGIN
     INSERT INTO [Identity].MenuList (MENUNAME,MENUNAMENEPALI,Icon,Path)
	 SELECT 'Document Management',N'कागजात व्यवस्थापन','fas fa-cog',''
END
IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Document Store')
BEGIN
     INSERT INTO [Identity].MenuList (MENUNAME,MENUNAMENEPALI,ParentId,Icon,Path)
	 SELECT 'Document Store',N'कागजात स्टोर',(SELECT TOP 1 ID FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Document Management'),'fas fa-paperclip','/Document-store'
END
IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Document Types')
BEGIN
     INSERT INTO [Identity].MenuList (MENUNAME,MENUNAMENEPALI,ParentId,Icon,Path)
	 SELECT 'Document Types',N'कागजात प्रकार',(SELECT TOP 1 ID FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Document Management'),'far fa-copy','/Document-types'
END

IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Administration')
BEGIN
     INSERT INTO [Identity].MenuList (MENUNAME,MENUNAMENEPALI,Icon,Path)
	 SELECT 'Administration',N'प्रशाशन','fas fa-cog',''
END
IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Users')
BEGIN
     INSERT INTO [Identity].MenuList (MENUNAME,MENUNAMENEPALI,ParentId,Icon,Path)
	 SELECT 'Users',N'प्रयोगकर्ता',(SELECT TOP 1 ID FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Administration'),'fas fa-User','/identity/users'
END

IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Roles')
BEGIN
     INSERT INTO [Identity].MenuList (MENUNAME,MENUNAMENEPALI,ParentId,Icon,Path)
	 SELECT 'Roles',N'रोल',(SELECT TOP 1 ID FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Administration'),'fas fa-User','/identity/roles'
END
IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Menu List')
BEGIN
     INSERT INTO [Identity].MenuList (MENUNAME,MENUNAMENEPALI,ParentId,Icon,Path)
	 SELECT 'Menu List',N'मेनु सुची',(SELECT TOP 1 ID FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Administration'),'fas fa-cog','/identity/menulist'
END
IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Menu Role')
BEGIN
     INSERT INTO [Identity].MenuList (MENUNAME,MENUNAMENEPALI,ParentId,Icon,Path)
	 SELECT 'Menu Role',N'मेनु रोल',(SELECT TOP 1 ID FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Administration'),'fas fa-cog','/identity/MenuRole'
END
IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Communication')
BEGIN
     INSERT INTO [Identity].MenuList (MENUNAME,MENUNAMENEPALI,Icon,Path)
	 SELECT 'Communication',N'संचार','fas fa-cog',''
END
IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Chat')
BEGIN
     INSERT INTO [Identity].MenuList (MENUNAME,MENUNAMENEPALI,ParentId,Icon,Path)
	 SELECT 'Chat',N'च्याट',(SELECT TOP 1 ID FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Communication'),'far fa-comment-dots','/chat'
END
IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Settings')
BEGIN
     INSERT INTO [Identity].MenuList (MENUNAME,MENUNAMENEPALI,Icon,Path)
	 SELECT 'Settings',N'सेटिंग','fas fa-cog',''
END
IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Gender')
BEGIN
     INSERT INTO [Identity].MenuList (MENUNAME,MENUNAMENEPALI,ParentId,Icon,Path)
	 SELECT 'Gender',N'लिङ्ग',(SELECT TOP 1 ID FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Settings'),'fas fa-mercury','/settings/genders'
END
IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Castes')
BEGIN
     INSERT INTO [Identity].MenuList (MENUNAME,MENUNAMENEPALI,ParentId,Icon,Path)
	 SELECT 'Castes',N'जाति',(SELECT TOP 1 ID FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Settings'),'fas fa-cog','/settings/castes'
END
IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Communities')
BEGIN
     INSERT INTO [Identity].MenuList (MENUNAME,MENUNAMENEPALI,ParentId,Icon,Path)
	 SELECT 'Communities',N'समुदाय',(SELECT TOP 1 ID FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Settings'),'fas fa-users','/settings/Communities'
END
IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Categories')
BEGIN
     INSERT INTO [Identity].MenuList (MENUNAME,MENUNAMENEPALI,ParentId,Icon,Path)
	 SELECT 'Categories',N'श्रेणी',(SELECT TOP 1 ID FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Settings'),'fas fa-cog','/settings/Categories'
END
IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Holiday Types')
BEGIN
     INSERT INTO [Identity].MenuList (MENUNAME,MENUNAMENEPALI,ParentId,Icon,Path)
	 SELECT 'Holiday Types',N'होलिडे टाईप',(SELECT TOP 1 ID FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Settings'),'fas fa-window-maximize','/settings/holidaytypes'
END
IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Holiday For')
BEGIN
     INSERT INTO [Identity].MenuList (MENUNAME,MENUNAMENEPALI,ParentId,Icon,Path)
	 SELECT 'Holiday For',N'होलिडे फर',(SELECT TOP 1 ID FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Settings'),'fas fa-window-maximize','/settings/holidayfor'
END
IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Holiday Setup')
BEGIN
     INSERT INTO [Identity].MenuList (MENUNAME,MENUNAMENEPALI,ParentId,Icon,Path)
	 SELECT 'Holiday Setup',N'होलिडे सेटअप',(SELECT TOP 1 ID FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Settings'),'fas fa-window-maximize','/settings/holidaysetup'
END
IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Calender')
BEGIN
     INSERT INTO [Identity].MenuList (MENUNAME,MENUNAMENEPALI,ParentId,Icon,Path)
	 SELECT 'Calender',N'क्यालेन्डर',(SELECT TOP 1 ID FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Settings'),'fas fa-calendar','/settings/calender'
END
IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Master Table Setup')
BEGIN
     INSERT INTO [Identity].MenuList (MENUNAME,MENUNAMENEPALI,ParentId,Icon,Path)
	 SELECT 'Master Table Setup',N'मास्टर टेबल सेटअप',(SELECT TOP 1 ID FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Settings'),'fas fa-table','/settings/mastertablesetup'
END
IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Table Setup')
BEGIN
     INSERT INTO [Identity].MenuList (MENUNAME,MENUNAMENEPALI,ParentId,Icon,Path)
	 SELECT 'Table Setup',N'टेबल सेटअप',(SELECT TOP 1 ID FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Settings'),'fas fa-table','/settings/tablesetup'
END
IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Branch')
BEGIN
     INSERT INTO [Identity].MenuList (MENUNAME,MENUNAMENEPALI,ParentId,Icon,Path)
	 SELECT 'Branch',N'साखा',(SELECT TOP 1 ID FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Settings'),'fas fa-code-branch','/settings/branch'
END
GO
IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Staff Setup')
BEGIN
     INSERT INTO [Identity].MenuList (MENUNAME,MENUNAMENEPALI,ParentId,Icon,Path)
	 SELECT 'Staff Setup',N'',(SELECT TOP 1 ID FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Settings'),'fas fa-code-branch','/settings/staffsetup'
END
GO
IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='GL Settings')
BEGIN
     INSERT INTO [Identity].MenuList (MENUNAME,MENUNAMENEPALI,ParentId,Icon,Path)
	 SELECT 'GL Settings',N'',(SELECT TOP 1 ID FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Settings'),'FA FA-GEAR','/settings/glSettings'
END
GO
IF NOT EXISTS(SELECT '' FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Salary GL Setup')
BEGIN
     INSERT INTO [Identity].MenuList (MENUNAME,MENUNAMENEPALI,ParentId,Icon,Path)
	 SELECT 'Salary GL Setup',N'',(SELECT TOP 1 ID FROM  [IDENTITY].MENULIST WITH(NOLOCK) WHERE MENUNAME='Settings'),'FA FA-GEAR','/settings/SalaryGLSetup'
END
